/**
 * Generates src/ui/tokens.ts from frontend/theme.json.
 *
 * The webapp's theme.json is the single source of truth for colour and radius
 * across both clients, so the app never hand-copies a hex value that can drift.
 * shadcn stores colours as bare HSL triplets ("199 89% 48%") for CSS
 * `hsl(var(--x))` interpolation; React Native needs a literal colour, so we
 * resolve them to hex here rather than at runtime.
 *
 * Run: npm run tokens
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const THEME = join(here, '..', '..', 'frontend', 'theme.json');
const OUT = join(here, '..', 'src', 'ui', 'tokens.ts');

/** "199 89% 48%" -> "#0b9ad8" */
function hslTripletToHex(triplet) {
  const m = String(triplet).trim().match(/^([\d.]+)\s+([\d.]+)%\s+([\d.]+)%$/);
  if (!m) throw new Error(`theme.json: cannot parse HSL triplet "${triplet}"`);
  const h = parseFloat(m[1]) / 360;
  const s = parseFloat(m[2]) / 100;
  const l = parseFloat(m[3]) / 100;

  if (s === 0) {
    const v = Math.round(l * 255);
    return `#${[v, v, v].map((c) => c.toString(16).padStart(2, '0')).join('')}`;
  }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const channel = (t) => {
    let x = t;
    if (x < 0) x += 1;
    if (x > 1) x -= 1;
    if (x < 1 / 6) return p + (q - p) * 6 * x;
    if (x < 1 / 2) return q;
    if (x < 2 / 3) return p + (q - p) * (2 / 3 - x) * 6;
    return p;
  };
  const rgb = [channel(h + 1 / 3), channel(h), channel(h - 1 / 3)];
  return `#${rgb.map((c) => Math.round(c * 255).toString(16).padStart(2, '0')).join('')}`;
}

// Only the tokens a mobile client actually renders. The webapp's sidebar-*
// and popover-* tokens have no analogue here; pulling them in would imply a
// shared surface that doesn't exist.
const SHARED = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
];

const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

function resolve(scheme, theme) {
  const out = {};
  for (const key of SHARED) {
    const raw = theme[scheme][key];
    if (raw === undefined) throw new Error(`theme.json: ${scheme}.${key} is missing`);
    out[camel(key)] = hslTripletToHex(raw);
  }
  return out;
}

const theme = JSON.parse(readFileSync(THEME, 'utf8'));
const light = resolve('light', theme);
const dark = resolve('dark', theme);
const radius = parseFloat(theme.radius) * 16; // theme.json stores rem

const fmt = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `    ${k}: '${v}',`)
    .join('\n');

const body = `// GENERATED by scripts/generate-tokens.mjs from frontend/theme.json — do not edit.
// Run \`npm run tokens\` after changing the webapp theme.
// Source theme: ${JSON.stringify(theme.name)}

export const palette = {
  light: {
${fmt(light)}
  },
  dark: {
${fmt(dark)}
  },
} as const;

/** Base corner radius in px, from theme.json \`radius\`. */
export const radiusBase = ${radius};

export type ColorToken = keyof typeof palette.light;
export type SchemeName = keyof typeof palette;
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`tokens: wrote ${OUT} (${SHARED.length} tokens x 2 schemes, radius ${radius}px)`);
