// GENERATED by scripts/generate-tokens.mjs from frontend/theme.json — do not edit.
// Run `npm run tokens` after changing the webapp theme.
// Source theme: "AquaMind Water Theme"

export const palette = {
  light: {
    background: '#ffffff',
    foreground: '#020817',
    card: '#ffffff',
    cardForeground: '#020817',
    primary: '#0da2e7',
    primaryForeground: '#f8fafc',
    secondary: '#f1f5f9',
    secondaryForeground: '#0f172a',
    muted: '#f1f5f9',
    mutedForeground: '#64748b',
    accent: '#20d3ee',
    accentForeground: '#0f172a',
    destructive: '#ef4444',
    destructiveForeground: '#f8fafc',
    border: '#e2e8f0',
    input: '#e2e8f0',
    ring: '#0da2e7',
    chart1: '#0da2e7',
    chart2: '#20d3ee',
    chart3: '#39c1ef',
    chart4: '#3c8cdd',
    chart5: '#2d6cd2',
  },
  dark: {
    background: '#020817',
    foreground: '#f8fafc',
    card: '#020817',
    cardForeground: '#f8fafc',
    primary: '#3ebaf4',
    primaryForeground: '#0f172a',
    secondary: '#1e293b',
    secondaryForeground: '#f8fafc',
    muted: '#1e293b',
    mutedForeground: '#94a3b8',
    accent: '#20d3ee',
    accentForeground: '#f8fafc',
    destructive: '#7f1d1d',
    destructiveForeground: '#f8fafc',
    border: '#1e293b',
    input: '#1e293b',
    ring: '#3ebaf4',
    chart1: '#3ebaf4',
    chart2: '#20d3ee',
    chart3: '#5accf2',
    chart4: '#5299e0',
    chart5: '#427bd7',
  },
} as const;

/** Base corner radius in px, from theme.json `radius`. */
export const radiusBase = 8;

export type ColorToken = keyof typeof palette.light;
export type SchemeName = keyof typeof palette;
