#!/usr/bin/env python3
"""
Simple Netlist Generator for ESP8266 Water Tank Monitoring System

This generates a text-based netlist/wiring reference without requiring
KiCad libraries or SKiDL's complex part system.

Usage:
    python3 generate_netlist.py
"""

def generate_netlist():
    """Generate a text-based netlist for the ESP8266 water tank monitoring system."""
    
    netlist = []
    netlist.append("=" * 70)
    netlist.append("ESP8266 Water Tank Monitoring System - Netlist")
    netlist.append("=" * 70)
    netlist.append("")
    
    # Components
    netlist.append("COMPONENTS:")
    netlist.append("-" * 70)
    netlist.append("C1      Capacitor      100uF          Power decoupling (5V)")
    netlist.append("C2      Capacitor      10uF           Power decoupling (3.3V)")
    netlist.append("R1      Resistor       4.7k           DS18B20 pull-up")
    netlist.append("R2      Resistor       10k            Echo voltage divider (top)")
    netlist.append("R3      Resistor       20k            Echo voltage divider (bottom)")
    netlist.append("R4      Resistor       100k           Battery divider (top)")
    netlist.append("R5      Resistor       100k           Battery divider (bottom)")
    netlist.append("R6      Resistor       220            LED current limiting")
    netlist.append("D1      Diode          1N5819         Reverse polarity protection (optional)")
    netlist.append("U1      ESP8266        NodeMCU        Main microcontroller")
    netlist.append("U2      Sensor         DS18B20        Temperature sensor")
    netlist.append("U3      Sensor         HC-SR04        Ultrasonic sensor (or JSN-SR04T)")
    netlist.append("BZ1     Buzzer         Passive        Alert buzzer")
    netlist.append("LED1    LED            Standard        Status LED")
    netlist.append("J1      Connector     2-pin           Power input")
    netlist.append("J2      Connector     2-pin           Battery connector")
    netlist.append("")
    
    # Nets
    netlist.append("NETS:")
    netlist.append("-" * 70)
    netlist.append("VCC_5V:")
    netlist.append("  - C1.1")
    netlist.append("  - U3.VCC")
    netlist.append("  - J1.1")
    netlist.append("")
    netlist.append("VCC_3V3:")
    netlist.append("  - C2.1")
    netlist.append("  - U1.3V3")
    netlist.append("  - U2.VDD")
    netlist.append("  - R1.1")
    netlist.append("")
    netlist.append("GND:")
    netlist.append("  - C1.2")
    netlist.append("  - C2.2")
    netlist.append("  - U1.GND")
    netlist.append("  - U2.GND")
    netlist.append("  - U3.GND")
    netlist.append("  - BZ1.-")
    netlist.append("  - LED1.K")
    netlist.append("  - R3.2")
    netlist.append("  - R5.2")
    netlist.append("  - J1.2")
    netlist.append("  - J2.2")
    netlist.append("")
    netlist.append("GPIO0 (D3):")
    netlist.append("  - U1.GPIO0")
    netlist.append("  - U2.DQ")
    netlist.append("  - R1.2")
    netlist.append("")
    netlist.append("GPIO4 (D2):")
    netlist.append("  - U1.GPIO4")
    netlist.append("  - R2.2 (ECHO_MID)")
    netlist.append("")
    netlist.append("GPIO5 (D1):")
    netlist.append("  - U1.GPIO5")
    netlist.append("  - U3.Trig")
    netlist.append("")
    netlist.append("GPIO14 (D5):")
    netlist.append("  - U1.GPIO14")
    netlist.append("  - BZ1.+")
    netlist.append("")
    netlist.append("GPIO16:")
    netlist.append("  - U1.GPIO16")
    netlist.append("  - R6.1")
    netlist.append("")
    netlist.append("ADC0 (A0):")
    netlist.append("  - U1.ADC")
    netlist.append("  - R4.2")
    netlist.append("  - R5.1")
    netlist.append("")
    netlist.append("ECHO_MID:")
    netlist.append("  - U3.Echo")
    netlist.append("  - R2.1")
    netlist.append("  - R3.1")
    netlist.append("")
    netlist.append("BATTERY_PLUS:")
    netlist.append("  - J2.1")
    netlist.append("  - D1.A (if using protection)")
    netlist.append("  - R4.1")
    netlist.append("")
    netlist.append("BATTERY_PROTECTED:")
    netlist.append("  - D1.K (if using protection)")
    netlist.append("  - R4.1 (connect here instead of BATTERY_PLUS if using diode)")
    netlist.append("")
    netlist.append("LED_ANODE:")
    netlist.append("  - R6.2")
    netlist.append("  - LED1.A")
    netlist.append("")
    
    # Pin connections table
    netlist.append("")
    netlist.append("=" * 70)
    netlist.append("PIN CONNECTION TABLE")
    netlist.append("=" * 70)
    netlist.append("")
    netlist.append("ESP8266 NodeMCU Pinout:")
    netlist.append("  D1 (GPIO5)  -> U3.Trig (Ultrasonic Trigger)")
    netlist.append("  D2 (GPIO4)  -> R2.2 (Ultrasonic Echo via divider)")
    netlist.append("  D3 (GPIO0)  -> U2.DQ (Temperature sensor data)")
    netlist.append("  D5 (GPIO14) -> BZ1.+ (Buzzer positive)")
    netlist.append("  GPIO16      -> R6.1 (Status LED)")
    netlist.append("  A0 (ADC0)   -> R4.2 (Battery voltage divider)")
    netlist.append("  3.3V        -> VCC_3V3 net")
    netlist.append("  5V           -> VCC_5V net (if available)")
    netlist.append("  GND          -> GND net")
    netlist.append("")
    netlist.append("DS18B20 Temperature Sensor:")
    netlist.append("  Red (VDD)   -> VCC_3V3")
    netlist.append("  Black (GND) -> GND")
    netlist.append("  Yellow (DQ) -> GPIO0 (D3)")
    netlist.append("  Note: 4.7k pull-up resistor (R1) between VDD and DQ")
    netlist.append("")
    netlist.append("HC-SR04 / JSN-SR04T Ultrasonic Sensor:")
    netlist.append("  VCC (Red)   -> VCC_5V")
    netlist.append("  GND (Black) -> GND")
    netlist.append("  Trig (Yellow) -> GPIO5 (D1)")
    netlist.append("  Echo (Green)  -> GPIO4 (D2) via voltage divider")
    netlist.append("  Note: Voltage divider (R2=10k, R3=20k) for 5V to 3.3V conversion")
    netlist.append("")
    netlist.append("Buzzer:")
    netlist.append("  + -> GPIO14 (D5)")
    netlist.append("  - -> GND")
    netlist.append("")
    netlist.append("Status LED:")
    netlist.append("  Anode (+)   -> R6.2 (via 220Ω resistor)")
    netlist.append("  Cathode (-) -> GND")
    netlist.append("  R6.1        -> GPIO16")
    netlist.append("")
    netlist.append("Battery Monitoring:")
    netlist.append("  Battery +   -> J2.1 -> R4.1 (100k)")
    netlist.append("  R4.2        -> ADC0 (A0)")
    netlist.append("  R5.1        -> ADC0 (A0)")
    netlist.append("  R5.2        -> GND")
    netlist.append("  Battery -   -> J2.2 -> GND")
    netlist.append("  Note: 100k/100k divider provides 2:1 ratio (monitors up to 2V)")
    netlist.append("        For 12V battery, use 100k/10k ratio")
    netlist.append("")
    
    # Wiring notes
    netlist.append("=" * 70)
    netlist.append("WIRING NOTES")
    netlist.append("=" * 70)
    netlist.append("")
    netlist.append("1. Power Supply:")
    netlist.append("   - Primary: USB 5V via NodeMCU USB port")
    netlist.append("   - Backup: External battery via J2 connector")
    netlist.append("")
    netlist.append("2. Voltage Levels:")
    netlist.append("   - ESP8266 GPIO: 3.3V logic")
    netlist.append("   - Ultrasonic sensor: 5V (needs 5V power)")
    netlist.append("   - Echo pin: Use voltage divider for safety (R2/R3)")
    netlist.append("")
    netlist.append("3. OneWire Bus:")
    netlist.append("   - Requires 4.7k pull-up resistor (R1)")
    netlist.append("   - Connect between VCC_3V3 and DQ line")
    netlist.append("")
    netlist.append("4. Battery Monitoring:")
    netlist.append("   - ESP8266 ADC max input: 1V")
    netlist.append("   - 100k/100k divider allows monitoring up to 2V")
    netlist.append("   - For higher voltages, adjust divider ratio")
    netlist.append("")
    netlist.append("5. Optional Components:")
    netlist.append("   - D1 (1N5819): Reverse polarity protection for battery")
    netlist.append("   - If using D1, connect battery to D1.A, R4.1 to D1.K")
    netlist.append("")
    
    return "\n".join(netlist)


if __name__ == '__main__':
    netlist_text = generate_netlist()
    
    # Write to file
    with open('esp8266_water_tank_netlist.txt', 'w') as f:
        f.write(netlist_text)
    
    # Print to console
    print(netlist_text)
    print("\n" + "=" * 70)
    print("Netlist saved to: esp8266_water_tank_netlist.txt")
    print("=" * 70)




